title: Hans Halvorson
baseurl: "" # the subpath of your site, e.g., "/blog"

# Optional settings
author: Hans Halvorson
email: hhalvors@princeton.edu

plugins:
  - jekyll-scholar

scholar:
  style: apa
  source: ./_bibliography
  bibliography: hh.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  details_dir:     details
  query: "@*"
  cite_style: apa


